### ISSUE TITLE
fail when render status: :unprocessable_entity

### ISSUE THREAD

**Issue by nyrf** [SimoTod/alpine-turbo-drive-adapter#29]
```ruby
def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
```

```ruby
class Post < ApplicationRecord
  validates :title, presence: true
end
```

`new.html.erb`

```erb

<div x-data="{text: 'demo' }">
  <div x-text="text"></div>
</div>


<%= form_with(model: @post) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>
```

when title is blank and render 422 status,  alpine won't work.

**Comment by SimoTod** [comment]
Sorry, I'm not a ruby developer but I'm not totally sure this is the right repository. Unless we are saying that it would work as expected with only alpine and without the turbolinks bridge.

By the way, could you post the generated html please? Thanks

**Comment by nyrf** [comment]
```html
<div x-data="{text: 'demo' }">
  <div x-text="text">demo</div>
</div>
<form action="/posts" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="ufX5eM9Ld2hGYyia8R4zGAS_wFvwNHzv2-CsUV0UKuR1bEpPhfuqfXDgtHTV_gDecNDNzLV-ipvSCyWkzevp-w">
   <div class="form-group">
    <label for="post_title">
    <input type="text" name="post[title]" id="post_title" />
   </div>
  <div class="form-group">
    <input type="submit" name="commit" value="Save post" class=" btn btn-primary"/>
  </div>
</form>
```

**Comment by SimoTod** [comment]
Thanks, I'll have a look in the next few days and see if i can replicate.

**Comment by nyrf** [comment]
Thanks, i modified https://github.com/SimoTod/alpine-turbo-drive-adapter/blob/9bbfe00ab66656f007a2f8ff3a009212ad9d76f7/src/bridge.js#L89 to ` document.addEventListener('turbo:render', initCallback)` can make it works, I'm not sure if that's the right way.

**Comment by SimoTod** [comment]
I'll need to have a look. In Turbolinks, render gets called multiple times when you have cached previews which is not the best for Alpine. It seems weird that it calls render but it doesn't call load after maybe I can ask the guys at Turbo.

**Comment by SimoTod** [comment]
there's a `turbo:submit-end` that we might be able to use

**Comment by nyrf** [comment]
Thanks, you're right, i'll try again later.

**Comment by SimoTod** [comment]
if the code use turbo frames, it replaces the content and triggers the alpine update.
The problem seems to be when you don't use a frame. In that case, it doesn't seem to replace the content with the response but it just re-renders the old age but it doesn't trigger a load event.
To be fair, it seems like a turbo bug, if the page is replaced, it should trigger the load event at the end.

**Comment by nyrf** [comment]
Thanks for your reply, yes, the `turbo:load` won't be triggered, i will use turbo frame to submit form until there is a PR.

**Comment by KostasKostogloy** [comment]
@SimoTod `turbo:submit-end` doesn't seem to do the trick. I fixed it on my project by initializing alpine components on `turbo:render`.

`turbo:render` can trigger twice (when you visit a cached page) so it's not optimal, but I can't see a way around it 🤷‍♂️ 

If we use `turbo:render` listener, we can remove the one on `turbo:load`. Otherwise we would be initializing alpine components 2-3 times on each page visit (if we use both).

**Comment by SimoTod** [comment]
Thanks for your feedback. I need to think about that before switching to turbo:render.

4 works but it's based on the assumption that an internal behaviour of Turbo won't ever change (I don't think they state anywhere that a 422 refreshed the page) so maybe keep an eye on it until they tag the first stable release.

**Comment by SimoTod** [comment]
Better late than never. @nyrf @KostasKostogloy or anyone else following the bug report.
Could you test https://cdn.jsdelivr.net/gh/SimoTod/alpine-turbo-drive-adapter@bug/422-responses/dist/alpine-turbo-drive-adapter.min.js and let me know if it resolves your issues, please?
I decided not to use load because in some edge cases calling Alpine on the cached version would introduce some small bugs so I went down the turbo:submit-end route.

**Comment by KostasKostogloy** [comment]
@SimoTod thanks for your hard work 🙇‍♂️ 

I am going to test this in the next few days and get back to you.

**Comment by nyrf** [comment]
@SimoTod  Great, thanks. I've tested and it works.

**Comment by SimoTod** [comment]
Thanks for confirming @nyrf

**Comment by rickclare** [comment]
Thanks for the fix @SimoTod.  I've installed v1.0.3 of alpine-turbo-drive-adapter and performed some initial testing myself - the problems we were having around this issue look to be fixed in Firefox (v88) and Chrome (v90).  

However, for me at least, the problem still seems to exist in Safari (Safari v14.1, MacOS Big Sur 11.3).  Is anyone experiencing this issue in _Safari only_?

(Note that the workaround fix suggested in https://github.com/SimoTod/alpine-turbo-drive-adapter/issues/29#issuecomment-795150055 does "fix" the issue in all browsers that I've tested with, so perhaps there's some quirk of Safari that needs to be taken account of?)

**Comment by SimoTod** [comment]
The problem with using render is that it might break the page in other edge cases introducing flickerings, etc. I'll check safari tomorrow.

**Comment by SimoTod** [comment]
@rickclare It took less than expected. I was able to replicate it in Safari. 
1.0.4 should fix the issue. Thanks for reporting it.

**Comment by rickclare** [comment]
@SimoTod that's great, thank you for jumping on the fix so quickly. I'll do some more testing tomorrow to double check v1.0.4 in the browsers that I have access to (everything popular apart from MS Edge)

Thanks again.

**Comment by rickclare** [comment]
Hi @SimoTod I've performed some more testing with **v1.0.4**     
Unfortunately I'm still experiencing the issue in Safari (no problems in Firefox or Chrome)

If it helps with diagnosis - my scenario is a simple user-registration page (run-of-the-mill Ruby-on-Rails MVC), which has a the following tiny piece of Alpine markup on it.

```erb
<div class="app-environment" 
     x-data="{ visible: true }"
     x-on:click="visible = false" 
     x-show.transition.opacity.duration.400ms="visible">
  <%= Rails.env %>
</div>
```

Before submitting the registration form, the `<div>` hides itself on click (as expected).

After submitting the form with invalid values (i.e. a 422 response) the `<div>` no longer responds to a click (i.e. indicating that AlpineJS is not initialising itself properly)

After submitting the form with valid values (i.e. resulting in a redirect) the `<div>` hides itself on click (as expected).

I'm happy to keep testing any fixes that you release.  I would love to help with the fix itself, but my javascript-fu isn't advanced enough to be able to suggest a solution.

**Comment by SimoTod** [comment]
@rickclare I'm not a rail developer so I would need the response from the form submission if you can kindly send it over (The example I built in php is working okay in safari) 

You can get it from safari > right click > inspect element (you need to enable it in preferences if you haven't yet) > network tab > your request. I need the content of both the preview tab and headers tab.

Thanks

**Comment by rickclare** [comment]
@SimoTod No problem, here is the response from Safari's Network tab:

Headers:

```
Summary
URL: https://localhost:4443/register
Status: 422
Source: Network
Address: 127.0.0.1:4443
Initiator: 
localhost:1:882


Request
:method: POST
:scheme: https
:authority: localhost:4443
:path: /register
Content-Type: application/x-www-form-urlencoded;charset=UTF-8
Accept: text/vnd.turbo-stream.html, text/html, application/xhtml+xml
Accept-Encoding: gzip, deflate, br
Accept-Language: en-gb
Host: localhost:4443
Origin: https://localhost:4443
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15
Connection: keep-alive
Referer: https://localhost:4443/register
Content-Length: 121
Cookie: _secret_key=SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYSHNheFYySzVWVVZfdC1BQVFXd3VYU1Y1.Rpw0UKoGbo3ZvQa47y-y9Y8W047AMMJDIUuVfUoIPbc
X-CSRF-Token: cEEvCgR3DG17BBIYAmIiDR0OMxIANQVx82NrREGX-QDGvOcLLYDgXfSD

Response
:status: 422
Content-Type: text/html; charset=utf-8
X-XSS-Protection: 1; mode=block
Cache-Control: max-age=0, private, must-revalidate
Date: Fri, 30 Apr 2021 09:28:51 GMT
Content-Length: 4386
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
x-download-options: noopen
x-permitted-cross-domain-policies: none
cross-origin-window-policy: deny
x-request-id: FnqYt9qh_WhxX8QAAABH

Request Data
MIME Type: application/x-www-form-urlencoded;charset=UTF-8
_csrf_token: cEEvCgR3DG17BBIYAmIiDR0OMxIANQVx82NrREGX-QDGvOcLLYDgXfSD
member[email]: a@b.com
member[password]: 123456

```

Preview:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover">
  <meta charset="UTF-8" content="PTgQOh91D15hPgI3N0QiESAgLhsNBRdHuKqBIGDk7kThCicPqwYnUVAr" csrf-param="authenticity_token" method-param="_method" name="csrf-token">
  <link data-turbo-track="reload" rel="stylesheet" href="/css/app.css">
  <script data-turbo-track="reload" defer src="/js/app.js"></script>
</head>
<body>

<form action="/register" method="post"><input name="authenticity_token" type="hidden" value="PTgQOh91D15hPgI3N0QiESAgLhsNBRdHuKqBIGDk7kThCicPqwYnUVAr">
  <div class="notification is-danger">
    Something went wrong! Please check the errors below
  </div>

  <label for="member_email">Email address</label>
  <input id="member_email" name="member[email]" type="email" value="a@b.com">

  <label for="member_password">Password</label>
  <input id="member_password" name="member[password]" type="password">
  <span class="is-danger">should be at least 12 characters</span>

  <button class="button is-primary" data-form-target="button" type="submit">Register</button>
</form>

<div class="app-environment"
     x-data="{ visible: true }"
     x-on:click="visible = false"
     x-show="visible">
  Development
</div>

</html>
```

**Comment by rickclare** [comment]
@SimoTod Actually, ignore the above.  I was seeing a syntax error when testing v1.0.4 in Microsoft Edge for the following line, which lead me down a rabbit hole!  Perhaps it's my build system that's incorrect?

```
SCRIPT1002: SCRIPT1002: Syntax error
alpine-turbo-drive-adapter.esm.js (29,50)

29: el.setAttribute('data-alpine-was-cloaked', el.getAttribute('x-cloak') ?? '')
```

**Comment by SimoTod** [comment]
I believe edge doesn't support `??` so it needs to be transpiled properly. The cdn version should already be compatible with ms edge and possibly ie11

**Comment by rickclare** [comment]
@SimoTod thank you for your perseverance with this. I'll find some time tomorrow to test out the new version and report back. Have a great weekend.

**Comment by SimoTod** [comment]
> @SimoTod thank you for your perseverance with this. I'll find some time tomorrow to test out the new version and report back. Have a great weekend.

It will likely be Sunday. I decided to run a few more tests for both features first. 👍

**Comment by SimoTod** [comment]
Unfortunately, the Safari was still happening (some times was working and sometimes wasn't). I believe something to do with the submit-end event being triggered on the document before the page update and Safari ignoring the delayed callback once the DOM was updated.
I gave up and switched to turbo:render :)
I found out that Turbo adds a data-turbo-preview attribute when rendering the preview from the cache while waiting for the page so I can skip the first render event when Turbo triggers them twice.

**Comment by rickclare** [comment]
@SimoTod I've retested with scenario where I had the original issue, using **v1.1.0** and the problem is no longer there (i.e. my Alpine markup is working perfectly after submitting a form that returns a 422 response)

I successfully tested with the following browsers:

✅ Safari v14.1 (MacOS)
✅ Google Chrome v90.0 (MacOS)
✅ Firefox v88.0 (MacOS)
✅ iOS Safari v14.1 (on iPhone iOS 14.5)
✅ MS Edge v90.0 (Windows 10)
✅ Android Chrome v83 (on Android 11 - via Android Studio simulator)

Thanks again for your patience and getting this fixed so quickly, nice job.
